AuctionSystem/Controllers/MVC/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Auction.Database;
using System.Net.Http;
using Auction.Model.Message;
using System.Configuration;

namespace AuctionSystemWebApi.Controllers.MVC
{
    public class OrderController : Controller
    {
        //To get customer orders
        public ActionResult GetCustomerOrders()
        {
            LoginModelResponse customerinfo = (LoginModelResponse)Session["Customer"];
            OrdersResponse orders = new OrdersResponse();
            if (customerinfo != null)
            {
                ViewBag.LoginSuccess = "True";
                int customerid = customerinfo.CustomerId;
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("http://localhost:54713/api/");
                    //HTTP GET
                    var url = "Order/GetCustomerOrders?customerid=" + customerid;
                    var responseMessageTask = client.GetAsync(url);
                    responseMessageTask.Wait();

                    var result = responseMessageTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsAsync<OrdersResponse>();
                        readTask.Wait();
                        orders = readTask.Result;
                        return View(orders);

                    }
                    else //web api sent error response 
                    {
                        //log response status here..

                        ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                        return View(orders);
                    }
                }
            }
            else
            {
                return RedirectToActionPermanent("Index", "Login");
            }
        }

        //To display customer selected order
        [Route("Order/DisplayCustomerOrder")]
        public ActionResult DisplayCustomerOrder(int orderid)
        {
            LoginModelResponse customerinfo = (LoginModelResponse)Session["Customer"];
           
            if (customerinfo == null)
            {
                return RedirectToActionPermanent("Index", "Login");
            }
                ViewBag.LoginSuccess = "True";
            Order customerOrders = new Order();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(ConfigurationManager.AppSettings["WebApiBaseUrl"]);
                //HTTP GET
                var responseMessageTask = client.GetAsync("api/Order/GetOrder?orderid=" + orderid);
                responseMessageTask.Wait();
                var responseMessage = responseMessageTask.Result;
                if (responseMessage.IsSuccessStatusCode)
                {
                    var responseContentTask = responseMessage.Content.ReadAsAsync<Order>();
                    responseContentTask.Wait();
                    customerOrders = responseContentTask.Result;
                    return View("DisplayCustomerOrder", customerOrders); 
                }
                else //web api sent error response 
                {
                    return View("DisplayCustomerOrder", customerOrders);
                }
            }

        }
    }
}

AuctionSystem/Controllers/WEB API/AuctionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Auction.Model.Message;
using Auction.BusinessLogic;
using Auction.Model.Data;
using Auction.Model;

namespace AuctionSystemWebApi.Controllers
{
    public class AuctionController : ApiController
    {
        //To retreive user bids with customerid
        [Route("api/Auction/GetBidsByCustomerId")]
        public IHttpActionResult GetBidsByCustomerId(int customerId)
        {
            var response = CustomerAuction.GetCustomerBids(customerId);
            return Ok(response);
        }

        //To get user selected bid
        [Route("api/Auction/GetBid")]
        public IHttpActionResult GetBid(int auctionid)
        {
            var response = CustomerAuction.GetBid(auctionid);
            return Ok(response);
        }

        //To post customer bid
        [Route("api/Auction/CreateBid")]
        public IHttpActionResult CreateBid(AuctionRequest auction)
        {
            try
            {
                AuctionResponse auctionResponse = new AuctionResponse();
                if (!ModelState.IsValid)
                {
                    auctionResponse.Error = new Error() { Code = ErrorCodes.ModelStateInvalid, Message = "model state is not valid" };
                    return Ok(auctionResponse);
                }
                auctionResponse = CustomerAuction.CreateBid(auction);
                return Ok(auctionResponse);
            }
            catch (Exception ex)
            {
                return Ok(ex.Message);
            }
        }

        //To update customer bid
        [Route("api/Auction/UpdateBid")]
        public IHttpActionResult UpdateBid(Auction.Model.Message.Auction auction)
        {
            try
            {
                AuctionResponse auctionResponse = new AuctionResponse();
                if (!ModelState.IsValid)
                {
                    auctionResponse.Error = new Error() { Code = ErrorCodes.ModelStateInvalid, Message = "model state is not valid" };
                    return Ok(auctionResponse);
                }
                auctionResponse = CustomerAuction.UpdateCustomerBid(auction);
                return Ok(auctionResponse);
            }
            catch (Exception ex)
            {
                return Ok(ex.Message);
            }
        }
    }
}

AuctionSystem/Controllers/WEB API/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Auction.Model.Message;
using Auction.BusinessLogic;
using Auction.Model;
using Auction.Model.Data;

namespace AuctionSystemWebApi.Controllers
{
    public class ProductController : ApiController
    {
        // GET: api/Product/5
        [Route("api/Products")]
        public IHttpActionResult GetProductsByCustomerId(int customerid)
        {
            var products = CustomerProduct.GetCustomerProducts(customerid);
            return Ok(products);
        }

        [Route("api/Product/GetProduct")]
        public IHttpActionResult GetProduct(int productId)
        {
            var product = CustomerProduct.GetProduct(productId);
            return Ok(product);
        }

        //Retrieve all product types.
        [Route("api/Product/GetProductTypes")]
        public IHttpActionResult GetProductTypes()
        {
            ProductTypesResponse products = CustomerProduct.GetProductTypes();
            return Ok(products);
        }

        //To retrieve all products with product type id.
        [Route("api/Product/GetProductByProductTypeId")]
        public IHttpActionResult GetProductByProductTypeId(int productTypeId)
        {
            ProductResponse product = CustomerProduct.GetProductsByProductTypeId(productTypeId);
            return Ok(product);
        }

        // POST products to database
        [Route("api/CreateProduct")]
        public IHttpActionResult CreateProduct([FromBody]ProductRequest productRequest)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ProductResponse products = new ProductResponse();
                    products.Error = new Error { Code = ErrorCodes.ModelStateInvalid, Message = "Model state is invalid" };
                    return Ok(products);
                }
                var Product = CustomerProduct.CreateProduct(productRequest);
                return Ok(Product);
            }
            catch (Exception ex)
            {
                return Ok(ex.Message);
            }
        }

        // PUT: api/Product/5
        [Route("api/Product/UpdateProduct")]
        public IHttpActionResult UpdateProduct([FromBody] ProductRequest productRequest)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ProductResponse products = new ProductResponse();
                    products.Error = new Error { Code = ErrorCodes.ModelStateInvalid, Message = "Model state is invalid" };
                    return Ok(products);
                }
                var Product = CustomerProduct.UpdateProduct(productRequest);
                return Ok(Product);
            }
            catch (Exception ex)
            {
                return Ok(ex.Message);
            }
        }
    }
}

AuctionSystem/Views/Shared/LoginPartial.cshtml
@{
    ViewBag.Title = "Partial";
}

@if (ViewBag.LoginSuccess == "False")
{
    
        <ul class="nav navbar-nav navbar-right" style="font-size:large; color: white">
            <li>@Html.ActionLink("Register", "Index", "Register", new { id = "" }, null)</li>

            <li>@Html.ActionLink("Log in", "Index", "Login", new { id = "" }, null)</li>
        </ul>
       
        }

        else if (ViewBag.LoginSuccess == "True")
        {
        <ul class="nav navbar-nav navbar-right" style="font-size:large; color: white" >
            <li>@Html.ActionLink("Log Out", "LogOut", "Login", new { id = "" }, null)</li>
        </ul>
        }

AuctionSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header" style="font-size:large">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "ProductTypes", "Product", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse" style="font-size:large">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("My Products", "GetCustomerProducts", "Product", new { id = "" }, new { title = "Your Products" })</li>
                    <li>@Html.ActionLink("My Bids", "GetMyBids", "Auction")</li>
                    <li>@Html.ActionLink("Sell a Product", "SellProduct", "Product", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Orders", "GetCustomerOrders", "Order", new { area = "" }, null)</li>
                </ul>
            </div>


            <div class="navbar-collapse collapse">
                @Html.Partial("LoginPartial")
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @*<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>*@
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/validation")
    @RenderSection("scripts", required: false)
</body>
</html>